alias add="sudo pacman -Syu"
alias rem="sudo pacman -Rns"
alias cb="kitty +kitten clipboard"
alias cbp="kitty +kitten clipboard --get-clipboard"
alias hyprconf="nvim ~/.config/hypr/hyprland.conf"
alias csswaybar="env GTK_DEBUG=interactive waybar"
alias ff="fastfetch"
